import { seedUser, seedChallenges, seedCommitments, seedActivity } from '../data/seed';
const KEY='stedime-store-v1';
const clone=v=>JSON.parse(JSON.stringify(v));
export function getStore(){ const raw=localStorage.getItem(KEY); if(raw) return JSON.parse(raw); const initial={user:clone(seedUser),challenges:clone(seedChallenges),commitments:clone(seedCommitments),activity:clone(seedActivity),authenticated:true}; localStorage.setItem(KEY,JSON.stringify(initial)); return initial; }
export function setStore(next){ localStorage.setItem(KEY,JSON.stringify(next)); return next; }
export function resetStore(){ localStorage.removeItem(KEY); return getStore(); }
export function createAccount(payload){ const s=getStore(); s.user={id:'user-1',...payload}; s.authenticated=true; return setStore(s); }
export function signIn(){ const s=getStore(); s.authenticated=true; return setStore(s); }
export function signOut(){ const s=getStore(); s.authenticated=false; return setStore(s); }
export function createChallenge(payload){ const s=getStore(); const id=`challenge-${Date.now()}`; const duration=Number(payload.durationDays)||30; const start=new Date(payload.startDate||new Date()); const end=new Date(start); end.setDate(end.getDate()+duration-1); const item={id,title:payload.title,description:payload.description,target:`${payload.threshold} successful sessions`,durationDays:duration,startDate:start.toISOString(),endDate:end.toISOString(),frequency:payload.frequency,threshold:Number(payload.threshold)||1,reward:payload.reward,status:'active',completedSessions:0,missedSessions:0,lateSessions:0,streak:0,bestStreak:0,sessions:[{id:`session-${Date.now()}`,dueDate:new Date().toISOString(),status:'pending',proof:null}]}; s.challenges.unshift(item); return setStore(s); }
export function createCommitment(payload){ const s=getStore(); const item={id:`commitment-${Date.now()}`,...payload,streak:0,bestStreak:0,status:'active',history:[]}; s.commitments.unshift(item); return setStore(s); }
export function submitChallengeProof(id,{text,imageName}){ const s=getStore(); const c=s.challenges.find(x=>x.id===id); if(!c) return s; const now=new Date(); let pending=c.sessions.find(x=>x.status==='pending'); if(!pending){ pending={id:`session-${Date.now()}`,dueDate:now.toISOString(),status:'pending',proof:null}; c.sessions.push(pending); } const due=new Date(pending.dueDate).getTime(); const late=now.getTime()-due>24*60*60*1000; const proof={text:text?.trim()||'',imageName:imageName||null,submittedAt:now.toISOString()}; if(pending){ pending.status=late?'late':'completed'; pending.proof=proof; } c.completedSessions=Math.min(c.threshold, c.completedSessions+1); if(late)c.lateSessions+=1; c.streak+=1; c.bestStreak=Math.max(c.bestStreak,c.streak); s.activity.unshift({id:`a-${Date.now()}`,type:'proof',title:c.title,text:late?'Late proof accepted and streak preserved.':proof.text||'Proof submitted.',time:now.toISOString()}); return setStore(s); }
export function submitCommitmentCheckin(id,{text,imageName}){ const s=getStore(); const c=s.commitments.find(x=>x.id===id); if(!c)return s; const now=new Date(); c.history.unshift({date:now.toISOString(),status:'completed',proof:text?.trim()||'Check-in completed.',imageName:imageName||null}); c.streak+=1; c.bestStreak=Math.max(c.bestStreak,c.streak); s.activity.unshift({id:`a-${Date.now()}`,type:'proof',title:c.name,text:text?.trim()||'Check-in completed.',time:now.toISOString()}); return setStore(s); }
